print("Soma dos quadrados de três valores.")
num1 = float(input("Insira o primeiro número: "))
num2 = float(input("Insira o segundo número: "))
num3 = float(input("Insira o terceiro número: "))
print("A soma dos quadrados é: {:.2f}".format((num1 ** 2) + (num2 ** 2) + (num3 ** 2)))