print("Média Aritmética de quatro notas")
nota1 = float(input("Insira a primeira nota: "))
nota2 = float(input("Insira a segunda nota: "))
nota3 = float(input("Insira a terceira nota: "))
nota4 = float(input("Insira a quarta nota: "))
print("Média das notas: {:.3f}".format((nota1 + nota2 + nota3 + nota4) / 4))